/**
 * Simulates Runtype-style SSE for the fullscreen assistant demo.
 * Frames use `event: message` and JSON `data` with a top-level `type` field (Persona client stream format).
 */

const encoder = new TextEncoder();

function enqueueFrame(frames: Uint8Array[], payload: Record<string, unknown>): void {
  frames.push(encoder.encode(`event: message\ndata: ${JSON.stringify(payload)}\n\n`));
}

function buildDelayedStream(frames: Uint8Array[], delayMs: number): ReadableStream<Uint8Array> {
  let index = 0;
  return new ReadableStream<Uint8Array>({
    pull(controller) {
      return new Promise<void>((resolve) => {
        setTimeout(() => {
          if (index >= frames.length) {
            controller.close();
          } else {
            controller.enqueue(frames[index]);
            index += 1;
          }
          resolve();
        }, delayMs);
      });
    }
  });
}

/** Markdown streamed into the artifact pane (same copy as the former upsertArtifact content). */
export const FULLSCREEN_ASSISTANT_SPOTLIGHT_MARKDOWN = `# Runtype assistant spotlight

Use the \`/research\` tool against **acme.com** to pull positioning signals.

## Fit checklist

- Narrative alignment
- Technical integration path

[Get Started with Runtype](https://runtype.com)

---

### What this pane is showing

> **TL;DR** — You’re looking at **rendered Markdown** beside the thread, in a **near-fullscreen split**—the same “chat + canvas” rhythm as today’s flagship AI assistants, embedded on *your* domain.

**Rendered document, not source**

- Headings, lists, \`inline code\`, **bold**, *italic*, and [links](https://runtype.com) are typeset for **reading**, not pasted as plain text.
- Long-form answers, specs, and checklists stay **scannable** in the right-hand pane.

**Layout**

1. **Thread** — the conversation column on the left.
2. **Canvas** — the artifact column on the right (this document).
`;

/** Default artifact id for the scripted stream and file card (keep in sync). */
export const FULLSCREEN_ASSISTANT_DEMO_ARTIFACT_ID = "fullscreen-assistant-spotlight-1";

function buildFullscreenAssistantFileCardRaw(artifactId: string): string {
  return JSON.stringify({
    component: "FullscreenAssistantFileCard",
    props: {
      title: "Runtype assistant spotlight",
      subtitle: "Document · MD",
      artifactId
    }
  });
}

function pushArtifactOnlyFrames(
  frames: Uint8Array[],
  options?: { artifactId?: string; title?: string; chunkSize?: number }
): void {
  const id = options?.artifactId ?? FULLSCREEN_ASSISTANT_DEMO_ARTIFACT_ID;
  /** Omit "· MD" here — document preset appends \` · ${kind}\` in the toolbar. */
  const title = options?.title ?? "Runtype assistant spotlight";
  const chunkSize = options?.chunkSize ?? 44;

  enqueueFrame(frames, {
    type: "artifact_start",
    id,
    artifactType: "markdown",
    title
  });
  for (let i = 0; i < FULLSCREEN_ASSISTANT_SPOTLIGHT_MARKDOWN.length; i += chunkSize) {
    enqueueFrame(frames, {
      type: "artifact_delta",
      id,
      delta: FULLSCREEN_ASSISTANT_SPOTLIGHT_MARKDOWN.slice(i, i + chunkSize)
    });
  }
  enqueueFrame(frames, { type: "artifact_complete", id });
}

/**
 * Artifact stream only (no transcript). Kept for focused tests / reuse.
 */
export function createFullscreenAssistantArtifactStream(options?: {
  artifactId?: string;
  title?: string;
  chunkSize?: number;
  delayMs?: number;
}): ReadableStream<Uint8Array> {
  const frames: Uint8Array[] = [];
  pushArtifactOnlyFrames(frames, options);
  return buildDelayedStream(frames, options?.delayMs ?? 42);
}

/**
 * Single scripted stream: transcript lines (via `transcript_insert`) then the same artifact markdown stream.
 */
export function createFullscreenAssistantScriptedStream(options?: {
  artifactId?: string;
  title?: string;
  chunkSize?: number;
  /** Delay between each SSE frame (ms). */
  delayMs?: number;
}): ReadableStream<Uint8Array> {
  const delayMs = options?.delayMs ?? 42;
  const artifactId = options?.artifactId ?? FULLSCREEN_ASSISTANT_DEMO_ARTIFACT_ID;
  const frames: Uint8Array[] = [];
  const now = () => new Date().toISOString();

  enqueueFrame(frames, {
    type: "transcript_insert",
    message: {
      id: "m-intro",
      role: "assistant",
      content:
        "Here is a concise readout. Open the document on the right for the full spotlight draft.",
      createdAt: now()
    }
  });

  // Artifact card is now auto-generated by the widget from artifact_start events.
  // The demo overrides PersonaArtifactCard in the component registry to customize the card.

  enqueueFrame(frames, {
    type: "transcript_insert",
    message: {
      id: "m-user-followup",
      role: "user",
      content: "Tighten the checklist section and add one competitor callout.",
      createdAt: now()
    }
  });

  pushArtifactOnlyFrames(frames, { ...options, artifactId });
  return buildDelayedStream(frames, delayMs);
}
