import type { RuntypeFlowConfig } from "../index.js";

/**
 * Basic conversational assistant flow
 * This is the default flow for simple chat interactions
 */
export const CONVERSATIONAL_FLOW: RuntypeFlowConfig = {
  name: "Streaming Prompt Flow",
  description: "Streaming chat generated by the widget",
  steps: [
    {
      id: "widget_prompt",
      name: "Prompt",
      type: "prompt",
      enabled: true,
      config: {
        model: "nemotron-3-ultra-550b-a55b",
        responseFormat: "markdown",
        outputVariable: "prompt_result",
        userPrompt: "{{user_message}}",
        systemPrompt: "you are a helpful assistant, chatting with a user",
        previousMessages: "{{messages}}"
      }
    }
  ]
};
