import type { TravrseFlowConfig } from "../index.js";

/**
 * Basic conversational assistant flow
 * This is the default flow for simple chat interactions
 */
export const CONVERSATIONAL_FLOW: TravrseFlowConfig = {
  name: "Streaming Prompt Flow",
  description: "Streaming chat generated by the widget",
  steps: [
    {
      id: "widget_prompt",
      name: "Prompt",
      type: "prompt",
      enabled: true,
      config: {
        model: "meta/llama3.1-8b-instruct-free",
        response_format: "markdown",
        output_variable: "prompt_result",
        user_prompt: "{{user_message}}",
        system_prompt: "you are a helpful assistant, chatting with a user",
        previous_messages: "{{messages}}"
      }
    }
  ]
};
